livros = [
    {"Nome": "Pensamentos", "Autor": "Marco Aurélio", "Categoria": "Filosofia", "Ano": 180, "Disponibilidade": "Sim"},
    {"Nome": "O Príncipe", "Autor": "Nicolau Maquiavel", "Categoria": "Filosofia", "Ano": 1532, "Disponibilidade": "Sim"},
    {"Nome": "Dom Quixote", "Autor": "Miguel de Cervantes", "Categoria": "Clássico", "Ano": 1605, "Disponibilidade": "Não"},
    {"Nome": "A República", "Autor": "Platão", "Categoria": "Filosofia", "Ano": -375, "Disponibilidade": "Sim"},
    {"Nome": "1984", "Autor": "George Orwell", "Categoria": "Distopia", "Ano": 1949, "Disponibilidade": "Sim"},
    {"Nome": "O Grande Gatsby", "Autor": "F. Scott Fitzgerald", "Categoria": "Ficção", "Ano": 1925, "Disponibilidade": "Sim"},
    {"Nome": "Cem Anos de Solidão", "Autor": "Gabriel García Márquez", "Categoria": "Realismo Mágico", "Ano": 1967, "Disponibilidade": "Não"},
    {"Nome": "Moby Dick", "Autor": "Herman Melville", "Categoria": "Aventura", "Ano": 1851, "Disponibilidade": "Sim"},
    {"Nome": "Orgulho e Preconceito", "Autor": "Jane Austen", "Categoria": "Romance", "Ano": 1813, "Disponibilidade": "Sim"},
    {"Nome": "O Senhor dos Anéis", "Autor": "J.R.R. Tolkien", "Categoria": "Fantasia", "Ano": 1954, "Disponibilidade": "Sim"},
    {"Nome": "O Hobbit", "Autor": "J.R.R. Tolkien", "Categoria": "Fantasia", "Ano": 1937, "Disponibilidade": "Sim"},
    {"Nome": "Crime e Castigo", "Autor": "Fiódor Dostoiévski", "Categoria": "Clássico", "Ano": 1866, "Disponibilidade": "Não"},
    {"Nome": "O Processo", "Autor": "Franz Kafka", "Categoria": "Ficção", "Ano": 1925, "Disponibilidade": "Sim"},
    {"Nome": "A Divina Comédia", "Autor": "Dante Alighieri", "Categoria": "Poesia", "Ano": 1320, "Disponibilidade": "Sim"},
    {"Nome": "O Alquimista", "Autor": "Paulo Coelho", "Categoria": "Ficção", "Ano": 1888, "Disponibilidade": "Sim"},
    {"Nome": "Ensaio sobre a Cegueira", "Autor": "José Saramago", "Categoria": "Ficção", "Ano": 1995, "Disponibilidade": "Não"},
    {"Nome": "Os Lusíadas", "Autor": "Luís de Camões", "Categoria": "Poesia", "Ano": 1572, "Disponibilidade": "Sim"},
    {"Nome": "A Arte da Guerra", "Autor": "Sun Tzu", "Categoria": "Filosofia", "Ano": -500, "Disponibilidade": "Sim"},
    {"Nome": "Frankenstein", "Autor": "Mary Shelley", "Categoria": "Terror", "Ano": 1818, "Disponibilidade": "Sim"},
    {"Nome": "Drácula", "Autor": "Bram Stoker", "Categoria": "Terror", "Ano": 1897, "Disponibilidade": "Não"},
    {"Nome": "Admirável Mundo Novo", "Autor": "Aldous Huxley", "Categoria": "Distopia", "Ano": 1932, "Disponibilidade": "Sim"},
    {"Nome": "O Retrato de Dorian Gray", "Autor": "Oscar Wilde", "Categoria": "Clássico", "Ano": 1890, "Disponibilidade": "Sim"}
]
